[package]
name = "cargo-wasm"
version = "0.2.1"
authors = ["Paul Dorehill"]
edition = "2018"

[dependencies]
cargo_metadata = "0.12"
structopt = "0.3"
reqwest = { version = "0.10", features = ["blocking", "json"] }
tar = "0.4"
flate2 = "1.0"
log = "0.4"
env_logger = "0.8"